In [2]:
# necessary libraries
import pandas as pd
import numpy as np

In [ ]:
# load dataset which cleaned
dataset = pd.read_csv('/content/drive/MyDrive/TCS RIO/file_for_featureeng.csv')
train = pd.read_csv('/content/drive/MyDrive/TCS RIO/train.csv')
test = pd.read_csv('/content/drive/MyDrive/TCS RIO/test.csv')
unskewd_data = pd.read_csv('/content/drive/MyDrive/TCS RIO/data_after_removing_skewness.csv')

In [ ]:
# sample rows
dataset.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

   Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0          1    Inside  ...             0         0           0        0   
1          1       FR2  ...             0         0           0        0   
2          1    Inside  ...             0         0           0        0   
3          1    Corner  ...           272         0           0        0   
4          1       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0    Feb    2008        WD         Normal   208500.0  
1       0    May    2007        WD         Normal   181500.0  
2       0    Sep    2008        WD         Normal   223500.0  
3       0    Feb    2006        WD        Abnorml   140000.0  
4       0    Dec    2008        WD         Normal   250000.0  

[5 rows x 76 columns]

In [ ]:
dataset = dataset.set_index('Id')

In [ ]:
# check data info
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 1 to 2919
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     2919 non-null   int64  
 1   MSZoning       2919 non-null   object 
 2   LotFrontage    2919 non-null   float64
 3   LotArea        2919 non-null   int64  
 4   Street         2919 non-null   object 
 5   LotShape       2919 non-null   object 
 6   LandContour    2919 non-null   object 
 7   Utilities      2919 non-null   int64  
 8   LotConfig      2919 non-null   object 
 9   LandSlope      2919 non-null   object 
 10  Neighborhood   2919 non-null   object 
 11  Condition1     2919 non-null   object 
 12  Condition2     2919 non-null   object 
 13  BldgType       2919 non-null   object 
 14  HouseStyle     2919 non-null   object 
 15  OverallQual    2919 non-null   int64  
 16  OverallCond    2919 non-null   int64  
 17  YearBuilt      2919 non-null   int64  
 18  YearRemo

In [ ]:
# necessary processing
convert_into_cat = ['MSSubClass','YearBuilt','YearRemodAdd','GarageYrBlt','YrSold']
for i in convert_into_cat:
  dataset[i]= dataset[i].astype(str)

In [ ]:
# total categorical variables
cat_feat = list(dataset.loc[:,dataset.dtypes == 'object'].columns.values)
len(cat_feat)

28

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 1 to 2919
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     2919 non-null   object 
 1   MSZoning       2919 non-null   object 
 2   LotFrontage    2919 non-null   float64
 3   LotArea        2919 non-null   int64  
 4   Street         2919 non-null   object 
 5   LotShape       2919 non-null   object 
 6   LandContour    2919 non-null   object 
 7   Utilities      2919 non-null   int64  
 8   LotConfig      2919 non-null   object 
 9   LandSlope      2919 non-null   object 
 10  Neighborhood   2919 non-null   object 
 11  Condition1     2919 non-null   object 
 12  Condition2     2919 non-null   object 
 13  BldgType       2919 non-null   object 
 14  HouseStyle     2919 non-null   object 
 15  OverallQual    2919 non-null   int64  
 16  OverallCond    2919 non-null   int64  
 17  YearBuilt      2919 non-null   object 
 18  YearRemo

In [ ]:
cat_feat

['MSSubClass',
 'MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'Foundation',
 'Heating',
 'CentralAir',
 'GarageType',
 'GarageYrBlt',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition']

In [ ]:
# using get_dummies to for one hot encoding
dummy_drop = []
clean_data = dataset
for i in cat_feat:
    dummy_drop += [i + '_' + str(dataset[i].unique()[-1])]

data = pd.get_dummies(dataset, columns = cat_feat)
data = data.drop(dummy_drop, axis = 1)

In [ ]:
data.shape

(2919, 496)

In [ ]:
# drop sale price column
data=data.drop('SalePrice',axis=1)

In [ ]:
# Scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data_scaled = sc.fit_transform(data)

In [ ]:
# Split the data
train_len=len(train)
x_train = data_scaled[:train_len]
x_test = data_scaled[train_len:]
y_train = train['SalePrice'][:train_len]

In [ ]:
# check columns and rows in data
x_test.shape

(1459, 495)

In [ ]:
# Target variable
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [ ]:
# Build Linear Regression algorithm and fit on data
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
# predict and evaluate
from sklearn.metrics import r2_score
y_train_pred = lr.predict(x_train)
print(r2_score(y_train,y_train_pred))

0.9340798048600792


In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [ ]:
# Build Support Vector Machine algorithm fit,predict and evaluate with hyperparmater tuning
from sklearn.svm import SVR
kernel = ['linear','rbf','poly']
for i in kernel:
   SVM = SVR(kernel=i)
   SVM.fit(x_train,y_train)
   svm_pred = SVM.predict(x_train)
   r2=r2_score(svm_pred,y_train)
   print('r2_score is :',r2,'for',i,'kernel')

r2_score is : -17.768586038605275 for linear kernel
r2_score is : -10483347.019895922 for rbf kernel
r2_score is : -1757340.8696334523 for poly kernel


In [ ]:
# Try another ML algorithm Decision Tree
from sklearn.tree import DecisionTreeRegressor
for i in range(1,21):
  dt = DecisionTreeRegressor(criterion='squared_error',splitter='best',max_depth=i,random_state=60)
  dt.fit(x_train,y_train)
  dt_pred = dt.predict(x_train)
  r2_dt = r2_score(dt_pred,y_train)
  print('r2_score is',r2_dt,'with max_depth of:',i)

r2_score is -0.2008192398515074 with max_depth of: 1
r2_score is 0.42177861064837574 with max_depth of: 2
r2_score is 0.6568092912083735 with max_depth of: 3
r2_score is 0.7651772447920474 with max_depth of: 4
r2_score is 0.8397134367735823 with max_depth of: 5
r2_score is 0.8938783713012179 with max_depth of: 6
r2_score is 0.9317728705178837 with max_depth of: 7
r2_score is 0.9560625612724581 with max_depth of: 8
r2_score is 0.9711042073191462 with max_depth of: 9
r2_score is 0.9811711705160302 with max_depth of: 10
r2_score is 0.9882843309684506 with max_depth of: 11
r2_score is 0.9928631994489678 with max_depth of: 12
r2_score is 0.9955293819557364 with max_depth of: 13
r2_score is 0.9971173635233352 with max_depth of: 14
r2_score is 0.998121886678481 with max_depth of: 15
r2_score is 0.9987257035003329 with max_depth of: 16
r2_score is 0.9991416449800978 with max_depth of: 17
r2_score is 0.9994527165924394 with max_depth of: 18
r2_score is 0.9997463232295379 with max_depth of: 19
r

In [ ]:
# Another Algorithm - Gradient Boosting Regressor
from sklearn.ensemble import GradientBoostingRegressor
for i in range(1,11):
    GBR = GradientBoostingRegressor(learning_rate=0.2,max_depth=i)
    GBR.fit(x_train,y_train)
    gbr_pred=GBR.predict(x_train)
    r2_gbr = r2_score(gbr_pred,y_train)
    print('r2_score is:',r2_gbr,'for',i,'depth')

r2_score is: 0.9031127587879091 for 1 depth
r2_score is: 0.9526266161456748 for 2 depth
r2_score is: 0.9761297322249225 for 3 depth
r2_score is: 0.9879603141549449 for 4 depth
r2_score is: 0.994925935794624 for 5 depth
r2_score is: 0.998221701870164 for 6 depth
r2_score is: 0.99941199029828 for 7 depth
r2_score is: 0.999863500648871 for 8 depth
r2_score is: 0.9999812040564924 for 9 depth
r2_score is: 0.9999962740597583 for 10 depth


In [ ]:
# Select the model with best Hyperparameter
GBR = GradientBoostingRegressor(learning_rate=0.2,max_depth=9)
GBR.fit(x_train,y_train)
gbr_pred=GBR.predict(x_train)

In [ ]:
gbr_pred

array([207572.97656945, 181024.21640511, 223405.61253043, ...,
       266475.36721387, 142040.93503906, 147703.6112889 ])

In [ ]:
r2_score(gbr_pred,y_train)

0.9999812040564924

In [ ]:
y_pred_gbr=GBR.predict(x_test)

In [ ]:
y_pred_gbr

array([128565.46663694, 170008.79625062, 181849.68496284, ...,
       156076.83147599, 102088.74199475, 195094.07526493])

In [ ]:
# Feature Selection technique - Recursive Feature Elimination
from sklearn.feature_selection import RFE
rfe=RFE(lr)
rfe=rfe.fit(x_train,y_train)

In [ ]:
# Important features
list(zip(data.columns,rfe.ranking_))

[('LotFrontage', 73),
 ('LotArea', 43),
 ('Utilities', 151),
 ('OverallQual', 25),
 ('OverallCond', 36),
 ('MasVnrArea', 58),
 ('ExterQual', 40),
 ('ExterCond', 187),
 ('BsmtQual', 34),
 ('BsmtCond', 141),
 ('BsmtExposure', 55),
 ('BsmtFinType1', 182),
 ('BsmtFinSF1', 23),
 ('BsmtFinType2', 123),
 ('BsmtFinSF2', 24),
 ('BsmtUnfSF', 22),
 ('TotalBsmtSF', 21),
 ('HeatingQC', 108),
 ('Electrical', 173),
 ('1stFlrSF', 17),
 ('2ndFlrSF', 18),
 ('LowQualFinSF', 20),
 ('GrLivArea', 19),
 ('BsmtFullBath', 165),
 ('BsmtHalfBath', 226),
 ('FullBath', 163),
 ('HalfBath', 162),
 ('BedroomAbvGr', 39),
 ('KitchenAbvGr', 81),
 ('KitchenQual', 57),
 ('TotRmsAbvGrd', 64),
 ('Functional', 46),
 ('Fireplaces', 135),
 ('GarageFinish', 98),
 ('GarageCars', 33),
 ('GarageArea', 233),
 ('GarageQual', 164),
 ('GarageCond', 161),
 ('PavedDrive', 90),
 ('WoodDeckSF', 75),
 ('OpenPorchSF', 203),
 ('EnclosedPorch', 191),
 ('3SsnPorch', 172),
 ('ScreenPorch', 93),
 ('PoolArea', 68),
 ('MiscVal', 247),
 ('MSSubClas

In [ ]:
y_pred_rfe=rfe.predict(x_train)

In [ ]:
r2_score(y_pred_rfe,y_train)

0.30905201222211587

In [ ]:
# Random Forest algorithm
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(n_estimators=100,criterion='squared_error',random_state=80,max_depth=18,max_features=20)
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_train)

In [ ]:
# Evaluate the prediction
r2_score(rf_pred,y_train)

0.9697803401005757

In [ ]:
# Hyperparameter tuning for Random forest algorithm
for i in range(1,20):
  rfc= RandomForestRegressor(n_estimators=100,criterion='squared_error',random_state=80,max_depth=i)
  rfc.fit(x_train,y_train)
  rfc_pred=rfc.predict(x_train)
  score=r2_score(rfc_pred,y_train)
  print(i ,':',score)

1 : -0.25117266843415287
2 : 0.44827610304905396
3 : 0.6804198111679002
4 : 0.8068351972655914
5 : 0.8752355183935937
6 : 0.9166779618250874
7 : 0.941411794499819
8 : 0.9565449583456868
9 : 0.965482477679079
10 : 0.9705643073773421
11 : 0.9735775153492019
12 : 0.9747735829218677
13 : 0.9763797089893456
14 : 0.9760656962383871
15 : 0.9764505552474755
16 : 0.9767742638079218
17 : 0.9768193026463592
18 : 0.9768153949795827
19 : 0.9768336559727993


In [ ]:
# Get important features used for prediction
importances = rf.feature_importances_

# Sort the feature importance in descending order

sorted_indices = np.argsort(importances)[::-1]

feat_labels = data.columns

for i in range(x_train.shape[1]):
    print("%2d) %-*s %f" % (i + 1, 20, feat_labels[sorted_indices[i]],importances[sorted_indices[i]]))

 1) OverallQual          0.070289
 2) GrLivArea            0.065991
 3) TotalBsmtSF          0.061385
 4) KitchenQual          0.052896
 5) 1stFlrSF             0.049154
 6) GarageCars           0.045102
 7) GarageArea           0.035005
 8) ExterQual            0.033648
 9) BsmtFinSF1           0.029916
10) BsmtQual             0.029758
11) FullBath             0.026820
12) 2ndFlrSF             0.023646
13) MasVnrArea           0.022723
14) TotRmsAbvGrd         0.021884
15) GarageFinish         0.021336
16) LotArea              0.020149
17) LotFrontage          0.017472
18) BsmtFinType1         0.017397
19) Foundation_PConc     0.016003
20) Fireplaces           0.013768
21) MSSubClass_60        0.011675
22) OpenPorchSF          0.011516
23) HeatingQC            0.010573
24) WoodDeckSF           0.009945
25) BsmtUnfSF            0.008766
26) Foundation_CBlock    0.007185
27) SaleType_New         0.006962
28) MasVnrType_Stone     0.006628
29) BsmtExposure         0.006505
30) HalfBath  

 We  have selected first 20 important features and created a Final data for model building and prediction.

In [ ]:
# we selected first 20 important features and created a Final data for buidlin
datanew = data[['GrLivArea', 'OverallQual' ,'KitchenQual','GarageArea','GarageCars','TotalBsmtSF','ExterQual' ,'1stFlrSF' ,'BsmtQual','GarageFinish' ,'FullBath', 'TotRmsAbvGrd', 'Foundation_PConc','2ndFlrSF','BsmtFinSF1' ,'Fireplaces' ,'LotArea' ,'LotFrontage','MasVnrArea' ,'BsmtFinType1']]
datanew

GrLivArea  OverallQual  KitchenQual  GarageArea  GarageCars  \
Id                                                                  
1          1710            7            2       548.0         2.0   
2          1262            6            1       460.0         2.0   
3          1786            7            2       608.0         2.0   
4          1717            7            2       642.0         3.0   
5          2198            8            2       836.0         3.0   
...         ...          ...          ...         ...         ...   
2915       1092            4            1         0.0         0.0   
2916       1092            4            1       286.0         1.0   
2917       1224            5            1       576.0         2.0   
2918        970            5            1         0.0         0.0   
2919       2000            7            1       650.0         3.0   

      TotalBsmtSF  ExterQual  1stFlrSF  BsmtQual  GarageFinish  FullBath  \
Id                                                                         
1           856.0          2       856         2             1         2   
2          1262.0          1      1262         2             1         2   
3           920.0          2       920         2             1         2   
4           756.0          1       961         1             0         1   
5          1145.0          2      1145         2             1         2   
...           ...        ...       ...       ...           ...       ...   
2915        546.0          1       546         1             0         1   
2916        546.0          1       546         1             0         1   
2917       1224.0          1      1224         1             0         1   
2918        912.0          1       970         2             0         1   
2919        996.0          1       996         2             2         2   

      TotRmsAbvGrd  Foundation_PConc  2ndFlrSF  BsmtFinSF1  Fireplaces  \
Id                                                                       
1                8                 1       854       706.0           0   
2                6                 0         0       978.0           1   
3                6                 1       866       486.0           1   
4                7                 0       756       216.0           1   
5                9                 1      1053       655.0           1   
...            ...               ...       ...         ...         ...   
2915             5                 0       546         0.0           0   
2916             6                 0       546       252.0           0   
2917             7                 0         0      1224.0           1   
2918             6                 1         0       337.0           0   
2919             9                 1      1004       758.0           1   

      LotArea  LotFrontage  MasVnrArea  BsmtFinType1  
Id                                                    
1        8450         65.0       196.0             5  
2        9600         80.0         0.0             4  
3       11250         68.0       162.0             5  
4        9550         60.0         0.0             4  
5       14260         84.0       350.0             5  
...       ...          ...         ...           ...  
2915     1936         21.0         0.0             0  
2916     1894         21.0         0.0             2  
2917    20000        160.0         0.0             4  
2918    10441         62.0         0.0             5  
2919     9627         74.0        94.0             1  

[2919 rows x 20 columns]

In [ ]:
datanew.to_csv('housedata.csv')

In [ ]:
datanew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 1 to 2919
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   GrLivArea         2919 non-null   int64  
 1   OverallQual       2919 non-null   int64  
 2   KitchenQual       2919 non-null   int64  
 3   GarageArea        2919 non-null   float64
 4   GarageCars        2919 non-null   float64
 5   TotalBsmtSF       2919 non-null   float64
 6   ExterQual         2919 non-null   int64  
 7   1stFlrSF          2919 non-null   int64  
 8   BsmtQual          2919 non-null   int64  
 9   GarageFinish      2919 non-null   int64  
 10  FullBath          2919 non-null   int64  
 11  TotRmsAbvGrd      2919 non-null   int64  
 12  Foundation_PConc  2919 non-null   uint8  
 13  2ndFlrSF          2919 non-null   int64  
 14  BsmtFinSF1        2919 non-null   float64
 15  Fireplaces        2919 non-null   int64  
 16  LotArea           2919 non-null   int64  


In [ ]:
data['Fireplaces'].unique()

array([0, 1, 2, 3, 4])

We will test the model first on the data(with selected features) to check  how it is performing and tune & optimize if needed later then Build the final model

In [ ]:
# Scaling the data
data_scaled_new = sc.fit_transform(datanew)
x_train_new=data_scaled_new[:train_len]

In [ ]:
# fit the model on data
rf.fit(x_train_new,y_train)

RandomForestRegressor(max_depth=18, max_features=20, random_state=80)

In [ ]:
# predict the output for train dataset
x_pred_new = rf.predict(x_train_new)

In [ ]:
r2_score(x_pred_new,y_train)

0.9771690696644881

In [ ]:
x_test_new=data_scaled_new[train_len:]

In [ ]:
rf.predict(x_test_new)

array([127104.36909091, 156919.61      , 180663.63361111, ...,
       157152.37      , 108913.91666667, 218068.85      ])

In [ ]:
# Final Model
RF = RandomForestRegressor(n_estimators=100,criterion='squared_error',random_state=80,max_depth=18)

In [ ]:
# Spilt the data with important features
X_train = datanew[:train_len]
X_test = datanew[train_len:]

In [ ]:
# Create a pipeline for Scaling and fitting model
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
pipeline = Pipeline([('Scaler', StandardScaler(with_mean = False)),  # Applying StandardScaler to all columns
    ('Model',RF)
])

In [ ]:
# fit pipeline
pipeline.fit(X_train,y_train)

Pipeline(steps=[('Scaler', StandardScaler(with_mean=False)),
                ('Model',
                 RandomForestRegressor(max_depth=18, random_state=80))])

In [ ]:
#Evaluation how model is performing
pipeline.score(X_train,y_train)

0.9795576093045177

In [ ]:
r2_score(pipeline.predict(X_train),y_train)

0.9771684661743392

In [ ]:
np.round(pipeline.predict(X_test))

array([126834., 157702., 180884., ..., 157152., 108914., 217889.])

In [ ]:
# Final Prediction for test data for submission
y_pred=np.round(pipeline.predict(X_test))
submit_test = pd.concat([test['Id'],pd.DataFrame(y_pred)], axis=1)
submit_test.columns=['Id', 'SalePrice']
submit_test

Id  SalePrice
0     1461   126834.0
1     1462   157702.0
2     1463   180884.0
3     1464   181602.0
4     1465   199270.0
...    ...        ...
1454  2915    72009.0
1455  2916    83120.0
1456  2917   157152.0
1457  2918   108914.0
1458  2919   217889.0

[1459 rows x 2 columns]

In [ ]:
submit_test.to_csv('Predicted_for_test.csv')

In [ ]:
# create pkl file for flask deployment
import pickle
Reg_model = '/content/drive/MyDrive/TCS RIO/Regmodel.pkl'
reg_pkl = open(Reg_model,'wb')
pickle.dump(pipeline,reg_pkl)
reg_pkl.close()

In [ ]:
# check the working of model
Readmodel = open(Reg_model,'rb') # r-read,b-binary
tmp=pickle.load(Readmodel)
tmp

Pipeline(steps=[('Scaler', StandardScaler(with_mean=False)),
                ('Model',
                 RandomForestRegressor(max_depth=18, random_state=80))])

In [ ]:
tmp.predict(X_test)

array([126833.61909091, 157702.11      , 180883.63361111, ...,
       157152.37      , 108913.91666667, 217888.85      ])

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   GrLivArea         1459 non-null   int64  
 1   OverallQual       1459 non-null   int64  
 2   KitchenQual       1459 non-null   int64  
 3   GarageArea        1459 non-null   float64
 4   GarageCars        1459 non-null   float64
 5   TotalBsmtSF       1459 non-null   float64
 6   ExterQual         1459 non-null   int64  
 7   1stFlrSF          1459 non-null   int64  
 8   BsmtQual          1459 non-null   int64  
 9   GarageFinish      1459 non-null   int64  
 10  FullBath          1459 non-null   int64  
 11  TotRmsAbvGrd      1459 non-null   int64  
 12  Foundation_PConc  1459 non-null   uint8  
 13  2ndFlrSF          1459 non-null   int64  
 14  BsmtFinSF1        1459 non-null   float64
 15  Fireplaces        1459 non-null   int64  
 16  LotArea           1459 non-null   int64

In [ ]:
# Evaluation of the model
def evaluate(model,x_test,y_test):
    predictions = model.predict(x_test)
    errors = abs(predictions -y_test)
    mape = 100 * np.mean(errors /y_test)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    return accuracy

In [ ]:
predictions = pipeline.predict(X_train)

In [ ]:
predictions

array([206061.26666667, 177301.55527473, 222312.315     , ...,
       255074.        , 136346.25      , 145623.54      ])

In [ ]:
errors = abs(predictions -y_train.values)
errors

array([ 2438.73333333,  4198.44472527,  1187.685     , ...,
       11426.        ,  5778.75      ,  1876.46      ])

In [ ]:
mape = 100 * np.mean(errors /y_train.values)
mape

4.042091927115407

In [ ]:
np.mean(errors)

6802.5299350403875

In [ ]:
accuracy = evaluate(pipeline,X_train,y_train)

Model Performance
Average Error: 6802.5299 degrees.
Accuracy = 95.96%.
